version: "3"

services:
  goapp1:
    build:
      context: ./
      dockerfile: .setup/dev/Dockerfile
    entrypoint:
      [
        'CompileDaemon',
        '-directory=./',
        '-build=go build -o weather-by-cep /app/main.go',
        '-command=./weather-by-cep cep_validator',
      ]
    container_name: go_wbc1
    ports:
      - 8081:8081
    volumes:
      - .:/app

  goapp2:
    build:
      context: ./
      dockerfile: .setup/dev/Dockerfile
    entrypoint:
      [
        'CompileDaemon',
        '-directory=./',
        '-build=go build -o weather-by-cep /app/main.go',
        '-command=./weather-by-cep wbc',
      ]
    container_name: go_wbc2
    ports:
      - 8082:8082
    volumes:
      - .:/app

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      # - "8888:8888"   # Prometheus metrics exposed by the collector
      # - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411